### ISSUE TITLE
Error: undefined method `admin_route_prefix'

### ISSUE THREAD

**Issue by ausgates** [comfy/comfy-blog#50]
When I run `rails generate comfy:blog` or `rails generate comfy:gallery` I get this:

``` shell
/home/austin/.rvm/gems/ruby-2.2.2/gems/comfy_gallery-0.1.3/lib/comfy_gallery/engine.rb:11:in `block (2 levels) in <class:Engine>': undefined method `admin_route_prefix' for #<ComfortableMexicanSofa::Configuration:0x00000004fe2690> (NoMethodError)
    from /home/austin/.rvm/gems/ruby-2.2.2/gems/comfy_gallery-0.1.3/lib/comfy_gallery.rb:14:in `configure'
    from /home/austin/.rvm/gems/ruby-2.2.2/gems/comfy_gallery-0.1.3/lib/comfy_gallery/engine.rb:10:in `block in <class:Engine>'
    from /home/austin/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
    from /home/austin/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
    from /home/austin/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /home/austin/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
    from /home/austin/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
    from /home/austin/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
    from /home/austin/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
    from /home/austin/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
    from /home/austin/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
    from /home/austin/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
    from /home/austin/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
    from /home/austin/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
    from /home/austin/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
    from /home/austin/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
    from /home/austin/cms/config/environment.rb:5:in `<top (required)>'
    from /home/austin/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
    from /home/austin/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
    from /home/austin/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /home/austin/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
    from /home/austin/.rvm/gems/ruby-2.2.2/gems/spring-1.3.5/lib/spring/application.rb:92:in `preload'
    from /home/austin/.rvm/gems/ruby-2.2.2/gems/spring-1.3.5/lib/spring/application.rb:143:in `serve'
    from /home/austin/.rvm/gems/ruby-2.2.2/gems/spring-1.3.5/lib/spring/application.rb:131:in `block in run'
    from /home/austin/.rvm/gems/ruby-2.2.2/gems/spring-1.3.5/lib/spring/application.rb:125:in `loop'
    from /home/austin/.rvm/gems/ruby-2.2.2/gems/spring-1.3.5/lib/spring/application.rb:125:in `run'
    from /home/austin/.rvm/gems/ruby-2.2.2/gems/spring-1.3.5/lib/spring/application/boot.rb:18:in `<top (required)>'
    from /home/austin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/austin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from -e:1:in `<main>'
```

**Comment by GBH** [comment]
Seems like a comfy-gallery is complaining here. Unfortunately that gem is super old and won't work with current cms/blog. I started a full rewrite a while ago, but never finished.

**Comment by ausgates** [comment]
What about blog? Does that work with current version of CMS? I got the same error I believe when I tried to use it

**Comment by GBH** [comment]
Blog is completely rewritten for CMS v 2.0. This is not an issue anymore
